### Linear regression
Revision:

- Selecting dependent/independent variables
- Training a linear regression model
- Outputting the loss
- Outputting coefficients
- Generating new predictions
- Using linear regression model to impute missing values

In [3]:
# Load your cleaned version of the titanic dataset
# (if you don't already have a saved copy, do some basic cleaning and save a copy now)
import pandas as pd
import numpy as np

df = pd.read_csv('datasets/titanic.csv')
df.Fare.fillna(df.Fare.median(), inplace=True)
X = np.array(df.Fare).reshape(-1,1)
y = df.Survived

C:\Users\rball\AppData\Local\Temp\ipykernel_30672\2356328574.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Fare.fillna(df.Fare.median(), inplace=True)


In [1]:
# Select age as your dependent variable, and select any other variables that you'd like as your independent variable

In [ ]:
# Create a linear regression model to train on this data 

In [ ]:
# Output the loss of the model

In [ ]:
# Output the coefficient weights to see which features seem to be having the largest effect on the dependent variable
#(according to the model)

In [ ]:
# Create a new fake datapoint and generate a prediction from it

In [ ]:
# Consider how this technique could be used for imputing missing values more accurately than using the median value
# in some cases

In [ ]:
# Use a linear regression model to impute values for any of the continuous variables in the data in the previous uncleaned dataset

***

### Logistic regression
- A model to make categorical predictions (either binary or multi-class)

In [4]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803   7.8900  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
# This time select survived (a categorical feature) as the dependent variable using logistic regression

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [7]:
X = np.array(df[['Pclass','Parch','SibSp','Fare']])

y = df['Survived']

y.value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [ ]:
# Output the loss of the model (will need research)

In [8]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X, y)

LogisticRegression()

In [10]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [9]:
y_pred = model.predict(X)
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,

In [ ]:
# Output the coefficients of the model (the same as in linear regression)

In [12]:
model.coef_

array([[-0.69062914,  0.25240073, -0.14479629,  0.0050644 ]])

In [ ]:
# Create a new datapoint and output a prediction

In [14]:
model.predict_proba(X)[:,1]

array([0.21794066, 0.60535794, 0.24425467, 0.52667258, 0.24437154,
       0.24475357, 0.61639682, 0.22358694, 0.35241434, 0.38426009,
       0.27339835, 0.58566902, 0.24437154, 0.52646725, 0.24418849,
       0.40180043, 0.20604827, 0.39815416, 0.22736229, 0.24360086,
       0.41403128, 0.39815416, 0.24435209, 0.59662354, 0.22358694,
       0.52660929, 0.24360086, 0.83396319, 0.24421185, 0.24422737,
       0.58710711, 0.69186941, 0.2440911 , 0.39512418, 0.61845117,
       0.58180375, 0.24360478, 0.24437154, 0.20293317, 0.22140589,
       0.21986736, 0.3734503 , 0.24422737, 0.52287891, 0.24421185,
       0.24437154, 0.22514583, 0.2440911 , 0.20596376, 0.22718441,
       0.21493692, 0.24413783, 0.61192734, 0.379394  , 0.68523124,
       0.59662354, 0.39512418, 0.24360478, 0.50538554, 0.2402539 ,
       0.24360478, 0.64948628, 0.62000852, 0.27729503, 0.58710711,
       0.27193779, 0.39512418, 0.24447284, 0.23078628, 0.19539149,
       0.39512418, 0.2402539 , 0.47333386, 0.2242232 , 0.29245

***

Accuracy - https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html

In [ ]:
# Use your previous model, and the documentation above to output the accuracy score for your model

In [15]:
from sklearn.metrics import accuracy_score

In [17]:
accuracy_score(y, y_pred)

0.6879910213243546

In [22]:
df_pred = pd.DataFrame(y)
df_pred['y_pred'] = y_pred

df_pred.columns = ['y_true','y_pred']

pred_1_is_1 = df_pred.loc[(df_pred['y_true'] == 1) & (df_pred['y_pred'] == 1)]
pred_1_is_0 = df_pred.loc[(df_pred['y_true'] == 0) & (df_pred['y_pred'] == 1)]
pred_0_is_1 = df_pred.loc[(df_pred['y_true'] == 1) & (df_pred['y_pred'] == 0)]
pred_0_is_0 = df_pred.loc[(df_pred['y_true'] == 0) & (df_pred['y_pred'] == 0)]

print((len(pred_1_is_1) + len(pred_0_is_0))/len(df_pred))

0.6879910213243546


In [23]:
neg = 100000
pos = 100

print(100000/(100000+100))

0.999000999000999


***